export const fakeMovies = [
  {
    id: 'tt0111161',
    url: 'https://www.imdb.com/title/tt0111161/',
    primaryTitle: 'The Shawshank Redemption',
    originalTitle: 'The Shawshank Redemption',
    type: 'movie',
    description:
      'A banker convicted of uxoricide forms a friendship over a quarter century with a hardened convict, while maintaining his innocence and trying to remain hopeful through simple compassion.',
    primaryImage:
      'https://m.media-amazon.com/images/M/MV5BMDAyY2FhYjctNDc5OS00MDNlLThiMGUtY2UxYWVkNGY2ZjljXkEyXkFqcGc@._V1_.jpg',
    contentRating: 'R',
    startYear: 1994,
    endYear: null,
    releaseDate: '1994-10-14',
    language: 'English',
    interests: ['Epic', 'Period Drama', 'Prison Drama', 'Drama'],
    countriesOfOrigin: ['United States'],
    externalLinks: [
      'https://www.facebook.com/shawshankredemptionfilm/',
      'https://www.warnerbros.com/movies/shawshank-redemption',
    ],
    spokenLanguages: ['English'],
    filmingLocations: [
      'Mansfield Reformatory - 100 Reformatory Road, Mansfield, Ohio, USA',
    ],
    budget: 25000000,
    grossWorldwide: 29332133,
    genres: ['Drama'],
    isAdult: false,
    runtimeMinutes: 142,
    averageRating: 9.3,
    numVotes: 2993473,
  },
  {
    id: 'tt0068646',
    url: 'https://www.imdb.com/title/tt0068646/',
    primaryTitle: 'The Godfather',
    originalTitle: 'The Godfather',
    type: 'movie',
    description:
      'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.',
    primaryImage:
      'https://m.media-amazon.com/images/M/MV5BYTJkNGQyZDgtZDQ0NC00MDM0LWEzZWQtYzUzZDEwMDljZWNjXkEyXkFqcGc@._V1_.jpg',
    contentRating: 'R',
    startYear: 1972,
    endYear: null,
    releaseDate: '1972-03-24',
    language: 'English',
    interests: ['Epic', 'Gangster', 'Tragedy', 'Crime', 'Drama'],
    countriesOfOrigin: ['United States'],
    externalLinks: [
      'https://www.facebook.com/thegodfather/',
      'https://www.instagram.com/thegodfathermovie/',
    ],
    spokenLanguages: ['English', 'Italian', 'Latin'],
    filmingLocations: ["Forza d'Agrò, Messina, Sicily, Italy"],
    budget: 6000000,
    grossWorldwide: 250342198,
    genres: ['Crime', 'Drama'],
    isAdult: false,
    runtimeMinutes: 175,
    averageRating: 9.2,
    numVotes: 2089453,
  },
  {
    id: 'tt0468569',
    url: 'https://www.imdb.com/title/tt0468569/',
    primaryTitle: 'The Dark Knight',
    originalTitle: 'The Dark Knight',
    type: 'movie',
    description:
      'When a menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman, James Gordon and Harvey Dent must work together to put an end to the madness.',
    primaryImage:
      'https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_.jpg',
    contentRating: 'PG-13',
    startYear: 2008,
    endYear: null,
    releaseDate: '2008-07-18',
    language: 'English',
    interests: [
      'Action Epic',
      'Epic',
      'Superhero',
      'Action',
      'Crime',
      'Drama',
      'Thriller',
    ],
    countriesOfOrigin: ['United States', 'United Kingdom'],
    externalLinks: [
      'https://www.facebook.com/darkknighttrilogy/',
      'https://www.warnerbros.co.uk/movies/dark-knight',
    ],
    spokenLanguages: ['English', 'Mandarin'],
    filmingLocations: ['Chicago, Illinois, USA'],
    budget: 185000000,
    grossWorldwide: 1009053678,
    genres: ['Action', 'Crime', 'Drama'],
    isAdult: false,
    runtimeMinutes: 152,
    averageRating: 9,
    numVotes: 2973235,
  },
  {
    id: 'tt0071562',
    url: 'https://www.imdb.com/title/tt0071562/',
    primaryTitle: 'The Godfather Part II',
    originalTitle: 'The Godfather Part II',
    type: 'movie',
    description:
      'The early life and career of Vito Corleone in 1920s New York City is portrayed, while his son, Michael, expands and tightens his grip on the family crime syndicate.',
    primaryImage:
      'https://m.media-amazon.com/images/M/MV5BNzc1OWY5MjktZDllMi00ZDEzLWEwMGItYjk1YmRhYjBjNTVlXkEyXkFqcGc@._V1_.jpg',
    contentRating: 'R',
    startYear: 1974,
    endYear: null,
    releaseDate: '1974-12-18',
    language: 'English',
    interests: ['Epic', 'Gangster', 'Tragedy', 'Crime', 'Drama'],
    countriesOfOrigin: ['United States'],
    externalLinks: [
      'https://www.facebook.com/thegodfather/',
      'https://twitter.com/godfathermovie',
    ],
    spokenLanguages: ['English', 'Italian', 'Spanish', 'Latin', 'Sicilian'],
    filmingLocations: [
      'Kaiser Estate, 4000 W Lake Blvd, Homewood, Lake Tahoe, California, USA',
    ],
    budget: 13000000,
    grossWorldwide: 47964222,
    genres: ['Crime', 'Drama'],
    isAdult: false,
    runtimeMinutes: 202,
    averageRating: 9,
    numVotes: 1409052,
  },
  {
    id: 'tt0050083',
    url: 'https://www.imdb.com/title/tt0050083/',
    primaryTitle: '12 Angry Men',
    originalTitle: '12 Angry Men',
    type: 'movie',
    description:
      'The jury in a New York City murder trial is frustrated by a single member whose skeptical caution forces them to more carefully consider the evidence before jumping to a hasty verdict.',
    primaryImage:
      'https://m.media-amazon.com/images/M/MV5BYjE4NzdmOTYtYjc5Yi00YzBiLWEzNDEtNTgxZGQ2MWVkN2NiXkEyXkFqcGc@._V1_.jpg',
    contentRating: 'Approved',
    startYear: 1957,
    endYear: null,
    releaseDate: '1957-04-10',
    language: 'English',
    interests: ['Legal Drama', 'Psychological Drama', 'Crime', 'Drama'],
    countriesOfOrigin: ['United States'],
    externalLinks: null,
    spokenLanguages: ['English'],
    filmingLocations: [
      'New York County Courthouse - 60 Centre Street, New York City, New York, USA',
    ],
    budget: 350000,
    grossWorldwide: 2945,
    genres: ['Crime', 'Drama'],
    isAdult: false,
    runtimeMinutes: 96,
    averageRating: 9,
    numVotes: 906287,
  },
  {
    id: 'tt0167260',
    url: 'https://www.imdb.com/title/tt0167260/',
    primaryTitle: 'The Lord of the Rings: The Return of the King',
    originalTitle: 'The Lord of the Rings: The Return of the King',
    type: 'movie',
    description:
      "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.",
    primaryImage:
      'https://m.media-amazon.com/images/M/MV5BMTZkMjBjNWMtZGI5OC00MGU0LTk4ZTItODg2NWM3NTVmNWQ4XkEyXkFqcGc@._V1_.jpg',
    contentRating: 'PG-13',
    startYear: 2003,
    endYear: null,
    releaseDate: '2003-12-17',
    language: 'English',
    interests: [
      'Adventure Epic',
      'Epic',
      'Fantasy Epic',
      'Mountain Adventure',
      'Quest',
      'Sword & Sorcery',
      'Tragedy',
      'Adventure',
      'Drama',
      'Fantasy',
    ],
    countriesOfOrigin: ['New Zealand', 'United States'],
    externalLinks: [
      'https://www.facebook.com/lordoftheringstrilogy',
      'http://www.lordoftherings.net/',
    ],
    spokenLanguages: ['English', 'Quenya', 'Old English', 'Sindarin'],
    filmingLocations: ['Hinuera Valley, Matamata, Waikato, New Zealand'],
    budget: 94000000,
    grossWorldwide: 1138263151,
    genres: ['Adventure', 'Drama', 'Fantasy'],
    isAdult: false,
    runtimeMinutes: 201,
    averageRating: 9,
    numVotes: 2048914,
  },
  {
    id: 'tt0108052',
    url: 'https://www.imdb.com/title/tt0108052/',
    primaryTitle: "Schindler's List",
    originalTitle: "Schindler's List",
    type: 'movie',
    description:
      'In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.',
    primaryImage:
      'https://m.media-amazon.com/images/M/MV5BNjM1ZDQxYWUtMzQyZS00MTE1LWJmZGYtNGUyNTdlYjM3ZmVmXkEyXkFqcGc@._V1_.jpg',
    contentRating: 'R',
    startYear: 1993,
    endYear: null,
    releaseDate: '1994-02-04',
    language: 'English',
    interests: [
      'Docudrama',
      'Epic',
      'Historical Epic',
      'Period Drama',
      'Prison Drama',
      'Biography',
      'Drama',
      'History',
    ],
    countriesOfOrigin: ['United States'],
    externalLinks: [
      'https://www.facebook.com/SchindlersListMovie/',
      'https://www.uphe.com/movies/schindlers-list',
    ],
    spokenLanguages: ['English', 'Hebrew', 'German', 'Polish', 'Latin'],
    filmingLocations: [
      'Auschwitz-Birkenau Concentration Camp, Oswiecim, Malopolskie, Poland',
    ],
    budget: 22000000,
    grossWorldwide: 322161245,
    genres: ['Biography', 'Drama', 'History'],
    isAdult: false,
    runtimeMinutes: 195,
    averageRating: 9,
    numVotes: 1500321,
  },
];
