#!/usr/bin/env node

import fs from 'fs';

const commitMsgFile = process.argv[2];
const commitMsg = fs.readFileSync(commitMsgFile, "utf8").trim();

// Regex to match the required format
const regex = /^(feat|fix|docs|chore|test|refactor)(\(.+\))?:\s.+/gm

if (!regex.test(commitMsg)) {
  console.error(
    `Error: Commit message must follow the format: 
    'feat/fix/docs/chore/test/refactor(optional scope): <message>'`
  );
  process.exit(1);
}

process.exit(0);